//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommLog_Convert {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SQL {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SQL() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CommLog_Convert.SQL", typeof(SQL).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   INSERT IGNORE
        ///INTO
        ///    command_21(
        ///        fs_flag,
        ///        fs_time,
        ///        terminal,
        ///        command,
        ///        ticket_type,
        ///        car_type,
        ///        receipt_time,
        ///        parking_ticket,
        ///        commuter_pass
        ///    )
        ///    VALUES(
        ///        &apos;{0}&apos;,
        ///        &apos;{1}&apos;,
        ///        &apos;{2}&apos;,
        ///        &apos;{3}&apos;,
        ///        &apos;{4}&apos;,
        ///        &apos;{5}&apos;,
        ///        &apos;{6}&apos;,
        ///        &apos;{7}&apos;,
        ///        &apos;{8}&apos;
        ///    ) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string COMMAND21_INSERT {
            get {
                return ResourceManager.GetString("COMMAND21_INSERT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   /*USE parking_area_oote;*/
        ///INSERT IGNORE INTO command_22(
        ///    fs_flag,
        ///    fs_time,
        ///    terminal_number,
        ///    command,
        ///    ticket_type,
        ///    car_type,
        ///    leaving_shedcol_time,
        ///    commuter_pass_over,
        ///    leaving_shedcol_ticket,
        ///    cash_unpaid,
        ///    accrued_payable,
        ///    coupon_ticket_used,
        ///    accounts_payable,
        ///    parking_time,
        ///    ticketing_device,
        ///    tenant,
        ///    receipt_time,
        ///    accommodation_discount,
        ///    z_2,
        ///    series_2,
        ///    coupon_ticket_used_details_1,
        ///    coupon_ticket_used_ [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string COMMAND22_INSERT {
            get {
                return ResourceManager.GetString("COMMAND22_INSERT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   INSERT IGNORE
        ///INTO
        ///    command_27(
        ///        fs_flag,
        ///        fs_time,
        ///        terminal_number,
        ///        command,
        ///        now_closing_date
        ///    )
        ///    VALUES(
        ///        &apos;{0}&apos;,
        ///        &apos;{1}&apos;,
        ///        &apos;{2}&apos;,
        ///        &apos;{3}&apos;,
        ///        &apos;{4}&apos;
        ///    ) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string COMMSND27_INSERT {
            get {
                return ResourceManager.GetString("COMMSND27_INSERT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SELECT
        ///    *
        ///FROM
        ///    closing_processed_data
        ///WHERE
        ///    closing_date = (
        ///        SELECT
        ///            MAX(closing_date)
        ///        FROM
        ///            closing_processed_data
        ///    ) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string GET_CLOSE_DATETIME {
            get {
                return ResourceManager.GetString("GET_CLOSE_DATETIME", resourceCulture);
            }
        }
    }
}
